### ISSUE TITLE
DDB Layer 구성

### ISSUE THREAD

**Issue by SeoSeongHo** [SeoSeongHo/SNUPA-BACKEND#6]
### DDB Layer 구성
AWS DynamoDB SDK 를 이용하여 구현

JPA 와 연동한 우아한 형제 기술 블로그의 예를 참고하여 구현할 예정

참고(https://woowabros.github.io/study/2019/06/05/spring-data-dynamodb-1.html)

**Comment by BaekGeunYoung** [comment]
흠 근데 모델 이름이 Setting이 어울릴 지 걍 User가 어울릴 지는 얘기해봐야 할듯
그리고 사용자 정보는 카카오에서 받아올 거니까 id 필드는 autogenerated로 하지 말고 카카오 유저 아이디 그대로 받아서 넣으면 될듯?

**Comment by SeoSeongHo** [comment]
지금은 세팅이랑 유저가 거의 비슷해서 그렇게 해도 상관없긴할듯..?  원랜 프로필(유저) 모델을 따로 빼려다 일단 저렇게 해놓음

그리고 id 필드는 그렇게 하는 게 좋을듯

우선 유저는 세팅모델이랑 분리한채로 하는게 추후에 좋을듯

**Comment by SeoSeongHo** [comment]
RDB 이용하기로 결정 (2020.03.02)
